### ISSUE TITLE
Empty Relationships Being Serialized as Attributes

### ISSUE THREAD

**Issue by GavinPower747** [codecutout/JsonApiSerializer#39]
Hey there,

We have a "Match" resource which we are serializing and sending to a client, within this match resource we have a relationship to a set of "Spectator" resources (Both have an Id property and are setup correctly) however there may not be any spectators watching a match so there is a possibility that this list can be empty.

When serializing the empty list it seems to put it as a attribute rather than a relationship. Whereas it seems to be setup correctly when there is at least one spectator in the list.

Is there any way around this?

Example Output:

```JSON
    "data": [
        {
            "type": "match",
            "id": "32737895-7e44-408e-914b-e70a578dde88",
            "links": {
                "self": "ommitted",
                "schema": "ommitted"
            },
            "attributes": {
                "shardId": "pc-eu",
                "createdAt": "2018-03-16T17:52:25.5652711Z",
                "duration": 1000,
                "stats": {},
                "tags": {},
                "spectators": {
                    "data": []
                },
                "patchVersion": "master"
            },
            "relationships": {
                "rosters": {
                    "data": [
                        //Many Rosters omitted for brevity
                    ]
                },
                "assets": {
                    "data": [
                        {
                            "id": "3f21af6f-6368-407a-bd59-cbf29bd0dca2",
                            "type": "asset"
                        }
                    ]
                }
            }
        }
    ]
```

**Comment by alex-davies** [comment]
That looks like a bug in the library. Thanks for raising it, i'm a bit surprised it wasn't encountered sooner

I have released a fix in the 1.2.1 version of the library, let me know if you still are getting issues.

**Comment by GavinPower747** [comment]
Perfect, I'll upgrade to the new version and test that out now.

**Comment by GavinPower747** [comment]
Seems to have done it, closing the issue.

**Comment by GavinPower747** [comment]
Actually wait no, it still seems to be mapping it as an attribute except now it's mapping it just as a null value rather than an object with empty data. The empty list issue is now fixed but handling null relationships that are still included will be serialized as attributes.

```JSON
"data": [
        {
            "type": "match",
            "id": "32737895-7e44-408e-914b-e70a578dde88",
            "links": {
                "self": "ommitted",
                "schema": "ommitted"
            },
            "attributes": {
                "shardId": "pc-eu",
                "createdAt": "2018-03-16T17:52:25.5652711Z",
                "duration": 1000,
                "stats": {},
                "tags": {},
                "spectators": null,
                "patchVersion": "master"
            },
            "relationships": {
                "rosters": {
                    "data": [
                        //Many Rosters omitted for brevity
                    ]
                },
                "assets": {
                    "data": [
                        {
                            "id": "3f21af6f-6368-407a-bd59-cbf29bd0dca2",
                            "type": "asset"
                        }
                    ]
                }
            }
        }
    ]
```

**Comment by alex-davies** [comment]
Looks like you have uncovered a new bug, it appears we are not doing null handling correctly. Rather embarrassingly there were tests to cover this exact case however the tests were asserting on the incorrect behaviour

Issue is sort of related to json.net not passing null values to custom converters (https://github.com/JamesNK/Newtonsoft.Json/issues/112) and as this library is essentially a bunch of custom converters we weren't even invoked for null values. However I think I have a workaround.

Try giving 1.2.2 a go, it should handle null values correctly

It should also be noted for empty to-one relationships we return null and for empty to-many relationships we should return empty list (http://jsonapi.org/format/#document-resource-object-related-resource-links). To stay truer to the spec if there is a null list it will be serialized as an empty list. This allows the consumer to destinguish the difference between between one-to-one relationships and one-to-many relationships when there is no value.

**Comment by cmeeren** [comment]
I still experience this with 1.2.2.

I have an `order` resource with a to-one relationship named `editing-user`. I always add a link to this relationship, but `Relationship.Data` may be null, and in that case JsonApiSerializer adds it to `attributes` (including the link) instead of `relationships`.

When `Relationship.Data` is null, I get the following output:

```json
{
    "data": {
        "type": "order",
        "id": "1",
        "attributes": {
            "editing-user": {
                "links": {
                    "related": "http://localhost:5000/orders/1/editing-user"
                }
            }
        }
```

When the relationship is not null, it's correctly placed in `relationships`.

**Comment by alastairtree** [comment]
Version 1.3 has fixed the issue for me, thanks.
